# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classla.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rclassla.proto\x12\x07\x63lassla\"\x1e\n\x0e\x41nalyzeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\".\n\x0c\x41nalyzeReply\x12\x1e\n\x06tokens\x18\x01 \x03(\x0b\x32\x0e.classla.Token\"$\n\x05Token\x12\r\n\x05lemma\x18\x01 \x01(\t\x12\x0c\n\x04upos\x18\x02 \x01(\t2G\n\x08\x41nalyzer\x12;\n\x07\x41nalyze\x12\x17.classla.AnalyzeRequest\x1a\x15.classla.AnalyzeReply\"\x00\x62\x06proto3')



_ANALYZEREQUEST = DESCRIPTOR.message_types_by_name['AnalyzeRequest']
_ANALYZEREPLY = DESCRIPTOR.message_types_by_name['AnalyzeReply']
_TOKEN = DESCRIPTOR.message_types_by_name['Token']
AnalyzeRequest = _reflection.GeneratedProtocolMessageType('AnalyzeRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEREQUEST,
  '__module__' : 'classla_pb2'
  # @@protoc_insertion_point(class_scope:classla.AnalyzeRequest)
  })
_sym_db.RegisterMessage(AnalyzeRequest)

AnalyzeReply = _reflection.GeneratedProtocolMessageType('AnalyzeReply', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEREPLY,
  '__module__' : 'classla_pb2'
  # @@protoc_insertion_point(class_scope:classla.AnalyzeReply)
  })
_sym_db.RegisterMessage(AnalyzeReply)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'classla_pb2'
  # @@protoc_insertion_point(class_scope:classla.Token)
  })
_sym_db.RegisterMessage(Token)

_ANALYZER = DESCRIPTOR.services_by_name['Analyzer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANALYZEREQUEST._serialized_start=26
  _ANALYZEREQUEST._serialized_end=56
  _ANALYZEREPLY._serialized_start=58
  _ANALYZEREPLY._serialized_end=104
  _TOKEN._serialized_start=106
  _TOKEN._serialized_end=142
  _ANALYZER._serialized_start=144
  _ANALYZER._serialized_end=215
# @@protoc_insertion_point(module_scope)
